### ISSUE TITLE
Crawler

### ISSUE THREAD

**Issue by cezarelnazli** [ioanungurean/taip#4]
- [x] README care să explice cum se rulează crawler-ul.
- [x] Adăugat un câmp la JSON-ul trimis care să spună din ce categorie face parte produsul (i.e., 'book', 'movie', 'music').
- [x] Cheia pentru API luată dintr-un environment variable.
- [x] Funcția respectivă trebuie să fie apelată pentru fiecare produs dintr-o categorie.
- [x] Teste.

**Comment by ilincute** [comment]
Fixed #4 partially
